version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8085:80"
    volumes:
      - ./src/twitter-clone:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/twitter-clone/storage/app/public/:/var/www/html/public/storage/
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel8
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/twitter-clone:/var/www/html
      - ./src/twitter-clone/storage/app/public/:/var/www/html/public/storage/
    ports:
      - "9000:9000"
    networks:
      - laravel
